package Ejemplo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of COUNTRIES.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CountriesModelohr implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** COUNTRY_ID. */
	private String countryId;

	/** COUNTRY_NAME. */
	private String countryName;

	/** REGIONS. */
	private RegionsModelohr regions;

	/** The set of LOCATIONS. */
	private Set<LocationsModelohr> locationsSet;

	/**
	 * Constructor.
	 */
	public CountriesModelohr() {
		this.locationsSet = new HashSet<LocationsModelohr>();
	}

	/**
	 * Set the COUNTRY_ID.
	 * 
	 * @param countryId
	 *            COUNTRY_ID
	 */
	public void setCountryId(String countryId) {
		this.countryId = countryId;
	}

	/**
	 * Get the COUNTRY_ID.
	 * 
	 * @return COUNTRY_ID
	 */
	public String getCountryId() {
		return this.countryId;
	}

	/**
	 * Set the COUNTRY_NAME.
	 * 
	 * @param countryName
	 *            COUNTRY_NAME
	 */
	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	/**
	 * Get the COUNTRY_NAME.
	 * 
	 * @return COUNTRY_NAME
	 */
	public String getCountryName() {
		return this.countryName;
	}

	/**
	 * Set the REGIONS.
	 * 
	 * @param regions
	 *            REGIONS
	 */
	public void setRegions(RegionsModelohr regions) {
		this.regions = regions;
	}

	/**
	 * Get the REGIONS.
	 * 
	 * @return REGIONS
	 */
	public RegionsModelohr getRegions() {
		return this.regions;
	}

	/**
	 * Set the set of the LOCATIONS.
	 * 
	 * @param locationsSet
	 *            The set of LOCATIONS
	 */
	public void setLocationsSet(Set<LocationsModelohr> locationsSet) {
		this.locationsSet = locationsSet;
	}

	/**
	 * Add the LOCATIONS.
	 * 
	 * @param locations
	 *            LOCATIONS
	 */
	public void addLocations(LocationsModelohr locations) {
		this.locationsSet.add(locations);
	}

	/**
	 * Get the set of the LOCATIONS.
	 * 
	 * @return The set of LOCATIONS
	 */
	public Set<LocationsModelohr> getLocationsSet() {
		return this.locationsSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((countryId == null) ? 0 : countryId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CountriesModelohr other = (CountriesModelohr) obj;
		if (countryId == null) {
			if (other.countryId != null) {
				return false;
			}
		} else if (!countryId.equals(other.countryId)) {
			return false;
		}
		return true;
	}

}
