package Ejemplo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of DEPARTMENTS.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class DepartmentsModelohr implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** DEPARTMENT_ID. */
	private Double departmentId;

	/** DEPARTMENT_NAME. */
	private String departmentName;

	/** EMPLOYEES. */
	private EmployeesModelohr managerIdemployees;

	/** LOCATIONS. */
	private LocationsModelohr locations;

	/** The set of EMPLOYEES. */
	private Set<EmployeesModelohr> employeesSet;

	/** The set of JOB_HISTORY. */
	private Set<JobHistoryModelohr> jobHistorySet;

	/**
	 * Constructor.
	 */
	public DepartmentsModelohr() {
		this.employeesSet = new HashSet<EmployeesModelohr>();
		this.jobHistorySet = new HashSet<JobHistoryModelohr>();
	}

	/**
	 * Set the DEPARTMENT_ID.
	 * 
	 * @param departmentId
	 *            DEPARTMENT_ID
	 */
	public void setDepartmentId(Double departmentId) {
		this.departmentId = departmentId;
	}

	/**
	 * Get the DEPARTMENT_ID.
	 * 
	 * @return DEPARTMENT_ID
	 */
	public Double getDepartmentId() {
		return this.departmentId;
	}

	/**
	 * Set the DEPARTMENT_NAME.
	 * 
	 * @param departmentName
	 *            DEPARTMENT_NAME
	 */
	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	/**
	 * Get the DEPARTMENT_NAME.
	 * 
	 * @return DEPARTMENT_NAME
	 */
	public String getDepartmentName() {
		return this.departmentName;
	}

	/**
	 * Set the EMPLOYEES.
	 * 
	 * @param managerIdemployees
	 *            EMPLOYEES
	 */
	public void setManagerIdemployees(EmployeesModelohr managerIdemployees) {
		this.managerIdemployees = managerIdemployees;
	}

	/**
	 * Get the EMPLOYEES.
	 * 
	 * @return EMPLOYEES
	 */
	public EmployeesModelohr getManagerIdemployees() {
		return this.managerIdemployees;
	}

	/**
	 * Set the LOCATIONS.
	 * 
	 * @param locations
	 *            LOCATIONS
	 */
	public void setLocations(LocationsModelohr locations) {
		this.locations = locations;
	}

	/**
	 * Get the LOCATIONS.
	 * 
	 * @return LOCATIONS
	 */
	public LocationsModelohr getLocations() {
		return this.locations;
	}

	/**
	 * Set the set of the EMPLOYEES.
	 * 
	 * @param employeesSet
	 *            The set of EMPLOYEES
	 */
	public void setEmployeesSet(Set<EmployeesModelohr> employeesSet) {
		this.employeesSet = employeesSet;
	}

	/**
	 * Add the EMPLOYEES.
	 * 
	 * @param employees
	 *            EMPLOYEES
	 */
	public void addEmployees(EmployeesModelohr employees) {
		this.employeesSet.add(employees);
	}

	/**
	 * Get the set of the EMPLOYEES.
	 * 
	 * @return The set of EMPLOYEES
	 */
	public Set<EmployeesModelohr> getEmployeesSet() {
		return this.employeesSet;
	}

	/**
	 * Set the set of the JOB_HISTORY.
	 * 
	 * @param jobHistorySet
	 *            The set of JOB_HISTORY
	 */
	public void setJobHistorySet(Set<JobHistoryModelohr> jobHistorySet) {
		this.jobHistorySet = jobHistorySet;
	}

	/**
	 * Add the JOB_HISTORY.
	 * 
	 * @param jobHistory
	 *            JOB_HISTORY
	 */
	public void addJobHistory(JobHistoryModelohr jobHistory) {
		this.jobHistorySet.add(jobHistory);
	}

	/**
	 * Get the set of the JOB_HISTORY.
	 * 
	 * @return The set of JOB_HISTORY
	 */
	public Set<JobHistoryModelohr> getJobHistorySet() {
		return this.jobHistorySet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((departmentId == null) ? 0 : departmentId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		DepartmentsModelohr other = (DepartmentsModelohr) obj;
		if (departmentId == null) {
			if (other.departmentId != null) {
				return false;
			}
		} else if (!departmentId.equals(other.departmentId)) {
			return false;
		}
		return true;
	}

}
