package Ejemplo;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of EMPLOYEES.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EmployeesModelohr implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** EMPLOYEE_ID. */
	private Double employeeId;

	/** FIRST_NAME. */
	private String firstName;

	/** LAST_NAME. */
	private String lastName;

	/** EMAIL. */
	private String email;

	/** PHONE_NUMBER. */
	private String phoneNumber;

	/** HIRE_DATE. */
	private Date hireDate;

	/** JOBS. */
	private JobsModelohr jobs;

	/** SALARY. */
	private Double salary;

	/** COMMISSION_PCT. */
	private Double commissionPct;

	/** EMPLOYEES. */
	private EmployeesModelohr managerIdemployees;

	/** DEPARTMENTS. */
	private DepartmentsModelohr departments;

	/** The set of DEPARTMENTS. */
	private Set<DepartmentsModelohr> departmentsSet;

	/** The set of EMPLOYEES. */
	private Set<EmployeesModelohr> employeesSet;

	/** The set of JOB_HISTORY. */
	private Set<JobHistoryModelohr> jobHistorySet;

	/**
	 * Constructor.
	 */
	public EmployeesModelohr() {
		this.departmentsSet = new HashSet<DepartmentsModelohr>();
		this.employeesSet = new HashSet<EmployeesModelohr>();
		this.jobHistorySet = new HashSet<JobHistoryModelohr>();
	}

	/**
	 * Set the EMPLOYEE_ID.
	 * 
	 * @param employeeId
	 *            EMPLOYEE_ID
	 */
	public void setEmployeeId(Double employeeId) {
		this.employeeId = employeeId;
	}

	/**
	 * Get the EMPLOYEE_ID.
	 * 
	 * @return EMPLOYEE_ID
	 */
	public Double getEmployeeId() {
		return this.employeeId;
	}

	/**
	 * Set the FIRST_NAME.
	 * 
	 * @param firstName
	 *            FIRST_NAME
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * Get the FIRST_NAME.
	 * 
	 * @return FIRST_NAME
	 */
	public String getFirstName() {
		return this.firstName;
	}

	/**
	 * Set the LAST_NAME.
	 * 
	 * @param lastName
	 *            LAST_NAME
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * Get the LAST_NAME.
	 * 
	 * @return LAST_NAME
	 */
	public String getLastName() {
		return this.lastName;
	}

	/**
	 * Set the EMAIL.
	 * 
	 * @param email
	 *            EMAIL
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Get the EMAIL.
	 * 
	 * @return EMAIL
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * Set the PHONE_NUMBER.
	 * 
	 * @param phoneNumber
	 *            PHONE_NUMBER
	 */
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	/**
	 * Get the PHONE_NUMBER.
	 * 
	 * @return PHONE_NUMBER
	 */
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	/**
	 * Set the HIRE_DATE.
	 * 
	 * @param hireDate
	 *            HIRE_DATE
	 */
	public void setHireDate(Date hireDate) {
		this.hireDate = hireDate;
	}

	/**
	 * Get the HIRE_DATE.
	 * 
	 * @return HIRE_DATE
	 */
	public Date getHireDate() {
		return this.hireDate;
	}

	/**
	 * Set the JOBS.
	 * 
	 * @param jobs
	 *            JOBS
	 */
	public void setJobs(JobsModelohr jobs) {
		this.jobs = jobs;
	}

	/**
	 * Get the JOBS.
	 * 
	 * @return JOBS
	 */
	public JobsModelohr getJobs() {
		return this.jobs;
	}

	/**
	 * Set the SALARY.
	 * 
	 * @param salary
	 *            SALARY
	 */
	public void setSalary(Double salary) {
		this.salary = salary;
	}

	/**
	 * Get the SALARY.
	 * 
	 * @return SALARY
	 */
	public Double getSalary() {
		return this.salary;
	}

	/**
	 * Set the COMMISSION_PCT.
	 * 
	 * @param commissionPct
	 *            COMMISSION_PCT
	 */
	public void setCommissionPct(Double commissionPct) {
		this.commissionPct = commissionPct;
	}

	/**
	 * Get the COMMISSION_PCT.
	 * 
	 * @return COMMISSION_PCT
	 */
	public Double getCommissionPct() {
		return this.commissionPct;
	}

	/**
	 * Set the EMPLOYEES.
	 * 
	 * @param managerIdemployees
	 *            EMPLOYEES
	 */
	public void setManagerIdemployees(EmployeesModelohr managerIdemployees) {
		this.managerIdemployees = managerIdemployees;
	}

	/**
	 * Get the EMPLOYEES.
	 * 
	 * @return EMPLOYEES
	 */
	public EmployeesModelohr getManagerIdemployees() {
		return this.managerIdemployees;
	}

	/**
	 * Set the DEPARTMENTS.
	 * 
	 * @param departments
	 *            DEPARTMENTS
	 */
	public void setDepartments(DepartmentsModelohr departments) {
		this.departments = departments;
	}

	/**
	 * Get the DEPARTMENTS.
	 * 
	 * @return DEPARTMENTS
	 */
	public DepartmentsModelohr getDepartments() {
		return this.departments;
	}

	/**
	 * Set the set of the DEPARTMENTS.
	 * 
	 * @param departmentsSet
	 *            The set of DEPARTMENTS
	 */
	public void setDepartmentsSet(Set<DepartmentsModelohr> departmentsSet) {
		this.departmentsSet = departmentsSet;
	}

	/**
	 * Add the DEPARTMENTS.
	 * 
	 * @param departments
	 *            DEPARTMENTS
	 */
	public void addDepartments(DepartmentsModelohr departments) {
		this.departmentsSet.add(departments);
	}

	/**
	 * Get the set of the DEPARTMENTS.
	 * 
	 * @return The set of DEPARTMENTS
	 */
	public Set<DepartmentsModelohr> getDepartmentsSet() {
		return this.departmentsSet;
	}

	/**
	 * Set the set of the EMPLOYEES.
	 * 
	 * @param employeesSet
	 *            The set of EMPLOYEES
	 */
	public void setEmployeesSet(Set<EmployeesModelohr> employeesSet) {
		this.employeesSet = employeesSet;
	}

	/**
	 * Add the EMPLOYEES.
	 * 
	 * @param employees
	 *            EMPLOYEES
	 */
	public void addEmployees(EmployeesModelohr employees) {
		this.employeesSet.add(employees);
	}

	/**
	 * Get the set of the EMPLOYEES.
	 * 
	 * @return The set of EMPLOYEES
	 */
	public Set<EmployeesModelohr> getEmployeesSet() {
		return this.employeesSet;
	}

	/**
	 * Set the set of the JOB_HISTORY.
	 * 
	 * @param jobHistorySet
	 *            The set of JOB_HISTORY
	 */
	public void setJobHistorySet(Set<JobHistoryModelohr> jobHistorySet) {
		this.jobHistorySet = jobHistorySet;
	}

	/**
	 * Add the JOB_HISTORY.
	 * 
	 * @param jobHistory
	 *            JOB_HISTORY
	 */
	public void addJobHistory(JobHistoryModelohr jobHistory) {
		this.jobHistorySet.add(jobHistory);
	}

	/**
	 * Get the set of the JOB_HISTORY.
	 * 
	 * @return The set of JOB_HISTORY
	 */
	public Set<JobHistoryModelohr> getJobHistorySet() {
		return this.jobHistorySet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((employeeId == null) ? 0 : employeeId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		EmployeesModelohr other = (EmployeesModelohr) obj;
		if (employeeId == null) {
			if (other.employeeId != null) {
				return false;
			}
		} else if (!employeeId.equals(other.employeeId)) {
			return false;
		}
		return true;
	}

}
