package Ejemplo;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of JOB_HISTORY.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class JobHistoryModelohr implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** EMPLOYEES. */
	private EmployeesModelohr employees;

	/** START_DATE. */
	private Date startDate;

	/** END_DATE. */
	private Date endDate;

	/** JOBS. */
	private JobsModelohr jobs;

	/** DEPARTMENTS. */
	private DepartmentsModelohr departments;

	/**
	 * Constructor.
	 */
	public JobHistoryModelohr() {
	}

	/**
	 * Set the EMPLOYEES.
	 * 
	 * @param employees
	 *            EMPLOYEES
	 */
	public void setEmployees(EmployeesModelohr employees) {
		this.employees = employees;
	}

	/**
	 * Get the EMPLOYEES.
	 * 
	 * @return EMPLOYEES
	 */
	public EmployeesModelohr getEmployees() {
		return this.employees;
	}

	/**
	 * Set the START_DATE.
	 * 
	 * @param startDate
	 *            START_DATE
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * Get the START_DATE.
	 * 
	 * @return START_DATE
	 */
	public Date getStartDate() {
		return this.startDate;
	}

	/**
	 * Set the END_DATE.
	 * 
	 * @param endDate
	 *            END_DATE
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * Get the END_DATE.
	 * 
	 * @return END_DATE
	 */
	public Date getEndDate() {
		return this.endDate;
	}

	/**
	 * Set the JOBS.
	 * 
	 * @param jobs
	 *            JOBS
	 */
	public void setJobs(JobsModelohr jobs) {
		this.jobs = jobs;
	}

	/**
	 * Get the JOBS.
	 * 
	 * @return JOBS
	 */
	public JobsModelohr getJobs() {
		return this.jobs;
	}

	/**
	 * Set the DEPARTMENTS.
	 * 
	 * @param departments
	 *            DEPARTMENTS
	 */
	public void setDepartments(DepartmentsModelohr departments) {
		this.departments = departments;
	}

	/**
	 * Get the DEPARTMENTS.
	 * 
	 * @return DEPARTMENTS
	 */
	public DepartmentsModelohr getDepartments() {
		return this.departments;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((employees == null) ? 0 : employees.hashCode());
		result = prime * result + ((startDate == null) ? 0 : startDate.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		JobHistoryModelohr other = (JobHistoryModelohr) obj;
		if (employees == null) {
			if (other.employees != null) {
				return false;
			}
		} else if (!employees.equals(other.employees)) {
			return false;
		}
		if (startDate == null) {
			if (other.startDate != null) {
				return false;
			}
		} else if (!startDate.equals(other.startDate)) {
			return false;
		}
		return true;
	}

}
