package Ejemplo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of JOBS.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class JobsModelohr implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** JOB_ID. */
	private String jobId;

	/** JOB_TITLE. */
	private String jobTitle;

	/** MIN_SALARY. */
	private Double minSalary;

	/** MAX_SALARY. */
	private Double maxSalary;

	/** The set of EMPLOYEES. */
	private Set<EmployeesModelohr> employeesSet;

	/** The set of JOB_HISTORY. */
	private Set<JobHistoryModelohr> jobHistorySet;

	/**
	 * Constructor.
	 */
	public JobsModelohr() {
		this.employeesSet = new HashSet<EmployeesModelohr>();
		this.jobHistorySet = new HashSet<JobHistoryModelohr>();
	}

	/**
	 * Set the JOB_ID.
	 * 
	 * @param jobId
	 *            JOB_ID
	 */
	public void setJobId(String jobId) {
		this.jobId = jobId;
	}

	/**
	 * Get the JOB_ID.
	 * 
	 * @return JOB_ID
	 */
	public String getJobId() {
		return this.jobId;
	}

	/**
	 * Set the JOB_TITLE.
	 * 
	 * @param jobTitle
	 *            JOB_TITLE
	 */
	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	/**
	 * Get the JOB_TITLE.
	 * 
	 * @return JOB_TITLE
	 */
	public String getJobTitle() {
		return this.jobTitle;
	}

	/**
	 * Set the MIN_SALARY.
	 * 
	 * @param minSalary
	 *            MIN_SALARY
	 */
	public void setMinSalary(Double minSalary) {
		this.minSalary = minSalary;
	}

	/**
	 * Get the MIN_SALARY.
	 * 
	 * @return MIN_SALARY
	 */
	public Double getMinSalary() {
		return this.minSalary;
	}

	/**
	 * Set the MAX_SALARY.
	 * 
	 * @param maxSalary
	 *            MAX_SALARY
	 */
	public void setMaxSalary(Double maxSalary) {
		this.maxSalary = maxSalary;
	}

	/**
	 * Get the MAX_SALARY.
	 * 
	 * @return MAX_SALARY
	 */
	public Double getMaxSalary() {
		return this.maxSalary;
	}

	/**
	 * Set the set of the EMPLOYEES.
	 * 
	 * @param employeesSet
	 *            The set of EMPLOYEES
	 */
	public void setEmployeesSet(Set<EmployeesModelohr> employeesSet) {
		this.employeesSet = employeesSet;
	}

	/**
	 * Add the EMPLOYEES.
	 * 
	 * @param employees
	 *            EMPLOYEES
	 */
	public void addEmployees(EmployeesModelohr employees) {
		this.employeesSet.add(employees);
	}

	/**
	 * Get the set of the EMPLOYEES.
	 * 
	 * @return The set of EMPLOYEES
	 */
	public Set<EmployeesModelohr> getEmployeesSet() {
		return this.employeesSet;
	}

	/**
	 * Set the set of the JOB_HISTORY.
	 * 
	 * @param jobHistorySet
	 *            The set of JOB_HISTORY
	 */
	public void setJobHistorySet(Set<JobHistoryModelohr> jobHistorySet) {
		this.jobHistorySet = jobHistorySet;
	}

	/**
	 * Add the JOB_HISTORY.
	 * 
	 * @param jobHistory
	 *            JOB_HISTORY
	 */
	public void addJobHistory(JobHistoryModelohr jobHistory) {
		this.jobHistorySet.add(jobHistory);
	}

	/**
	 * Get the set of the JOB_HISTORY.
	 * 
	 * @return The set of JOB_HISTORY
	 */
	public Set<JobHistoryModelohr> getJobHistorySet() {
		return this.jobHistorySet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((jobId == null) ? 0 : jobId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		JobsModelohr other = (JobsModelohr) obj;
		if (jobId == null) {
			if (other.jobId != null) {
				return false;
			}
		} else if (!jobId.equals(other.jobId)) {
			return false;
		}
		return true;
	}

}
