package Ejemplo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of LOCATIONS.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class LocationsModelohr implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** LOCATION_ID. */
	private Double locationId;

	/** STREET_ADDRESS. */
	private String streetAddress;

	/** POSTAL_CODE. */
	private String postalCode;

	/** CITY. */
	private String city;

	/** STATE_PROVINCE. */
	private String stateProvince;

	/** COUNTRIES. */
	private CountriesModelohr countries;

	/** The set of DEPARTMENTS. */
	private Set<DepartmentsModelohr> departmentsSet;

	/**
	 * Constructor.
	 */
	public LocationsModelohr() {
		this.departmentsSet = new HashSet<DepartmentsModelohr>();
	}

	/**
	 * Set the LOCATION_ID.
	 * 
	 * @param locationId
	 *            LOCATION_ID
	 */
	public void setLocationId(Double locationId) {
		this.locationId = locationId;
	}

	/**
	 * Get the LOCATION_ID.
	 * 
	 * @return LOCATION_ID
	 */
	public Double getLocationId() {
		return this.locationId;
	}

	/**
	 * Set the STREET_ADDRESS.
	 * 
	 * @param streetAddress
	 *            STREET_ADDRESS
	 */
	public void setStreetAddress(String streetAddress) {
		this.streetAddress = streetAddress;
	}

	/**
	 * Get the STREET_ADDRESS.
	 * 
	 * @return STREET_ADDRESS
	 */
	public String getStreetAddress() {
		return this.streetAddress;
	}

	/**
	 * Set the POSTAL_CODE.
	 * 
	 * @param postalCode
	 *            POSTAL_CODE
	 */
	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	/**
	 * Get the POSTAL_CODE.
	 * 
	 * @return POSTAL_CODE
	 */
	public String getPostalCode() {
		return this.postalCode;
	}

	/**
	 * Set the CITY.
	 * 
	 * @param city
	 *            CITY
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * Get the CITY.
	 * 
	 * @return CITY
	 */
	public String getCity() {
		return this.city;
	}

	/**
	 * Set the STATE_PROVINCE.
	 * 
	 * @param stateProvince
	 *            STATE_PROVINCE
	 */
	public void setStateProvince(String stateProvince) {
		this.stateProvince = stateProvince;
	}

	/**
	 * Get the STATE_PROVINCE.
	 * 
	 * @return STATE_PROVINCE
	 */
	public String getStateProvince() {
		return this.stateProvince;
	}

	/**
	 * Set the COUNTRIES.
	 * 
	 * @param countries
	 *            COUNTRIES
	 */
	public void setCountries(CountriesModelohr countries) {
		this.countries = countries;
	}

	/**
	 * Get the COUNTRIES.
	 * 
	 * @return COUNTRIES
	 */
	public CountriesModelohr getCountries() {
		return this.countries;
	}

	/**
	 * Set the set of the DEPARTMENTS.
	 * 
	 * @param departmentsSet
	 *            The set of DEPARTMENTS
	 */
	public void setDepartmentsSet(Set<DepartmentsModelohr> departmentsSet) {
		this.departmentsSet = departmentsSet;
	}

	/**
	 * Add the DEPARTMENTS.
	 * 
	 * @param departments
	 *            DEPARTMENTS
	 */
	public void addDepartments(DepartmentsModelohr departments) {
		this.departmentsSet.add(departments);
	}

	/**
	 * Get the set of the DEPARTMENTS.
	 * 
	 * @return The set of DEPARTMENTS
	 */
	public Set<DepartmentsModelohr> getDepartmentsSet() {
		return this.departmentsSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((locationId == null) ? 0 : locationId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		LocationsModelohr other = (LocationsModelohr) obj;
		if (locationId == null) {
			if (other.locationId != null) {
				return false;
			}
		} else if (!locationId.equals(other.locationId)) {
			return false;
		}
		return true;
	}

}
