package Ejemplo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of REGIONS.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RegionsModelohr implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** REGION_ID. */
	private Integer regionId;

	/** REGION_NAME. */
	private String regionName;

	/** The set of COUNTRIES. */
	private Set<CountriesModelohr> countriesSet;

	/**
	 * Constructor.
	 */
	public RegionsModelohr() {
		this.countriesSet = new HashSet<CountriesModelohr>();
	}

	/**
	 * Set the REGION_ID.
	 * 
	 * @param regionId
	 *            REGION_ID
	 */
	public void setRegionId(Integer regionId) {
		this.regionId = regionId;
	}

	/**
	 * Get the REGION_ID.
	 * 
	 * @return REGION_ID
	 */
	public Integer getRegionId() {
		return this.regionId;
	}

	/**
	 * Set the REGION_NAME.
	 * 
	 * @param regionName
	 *            REGION_NAME
	 */
	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}

	/**
	 * Get the REGION_NAME.
	 * 
	 * @return REGION_NAME
	 */
	public String getRegionName() {
		return this.regionName;
	}

	/**
	 * Set the set of the COUNTRIES.
	 * 
	 * @param countriesSet
	 *            The set of COUNTRIES
	 */
	public void setCountriesSet(Set<CountriesModelohr> countriesSet) {
		this.countriesSet = countriesSet;
	}

	/**
	 * Add the COUNTRIES.
	 * 
	 * @param countries
	 *            COUNTRIES
	 */
	public void addCountries(CountriesModelohr countries) {
		this.countriesSet.add(countries);
	}

	/**
	 * Get the set of the COUNTRIES.
	 * 
	 * @return The set of COUNTRIES
	 */
	public Set<CountriesModelohr> getCountriesSet() {
		return this.countriesSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((regionId == null) ? 0 : regionId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		RegionsModelohr other = (RegionsModelohr) obj;
		if (regionId == null) {
			if (other.regionId != null) {
				return false;
			}
		} else if (!regionId.equals(other.regionId)) {
			return false;
		}
		return true;
	}

}
