CREATE DATABASE UD2;
CREATE USER 'ejemplo' IDENTIFIED BY 'ejemplo';
GRANT ALL PRIVILEGES ON UD2.* TO 'ejemplo';
FLUSH PRIVILEGES;

USE UD2;

CREATE TABLE PRODUCTOS (
	ID INT NOT NULL AUTO_INCREMENT,
	Descripcion VARCHAR(50) NOT NULL,
	StockActual INT,
	StockMinimo INT,
	PVP FLOAT NULL DEFAULT '0',
	PRIMARY KEY(ID)
);

CREATE TABLE CLIENTES (
	ID INT NOT NULL AUTO_INCREMENT,
	Nombre VARCHAR(50),
	Direccion VARCHAR(50),
	Poblacion VARCHAR(50),
	Telef VARCHAR(20),
	Nif VARCHAR(10),
	PRIMARY KEY(ID)
);


CREATE TABLE VENTAS (
	IDVenta INT NOT NULL ,
	FechaVenta DATE NOT NULL,
	IDCliente INT,
	IDProducto INT,
	Cantidad INT,
	PRIMARY KEY(IDVenta),
	CONSTRAINT FK__clientes FOREIGN KEY (IDCliente) REFERENCES CLIENTES(ID),
	CONSTRAINT FK__productos FOREIGN KEY (IDProducto) REFERENCES PRODUCTOS(ID)
);
